name: Build

on: [pull_request, push]

jobs: 
  build:
    container:
      image: ghcr.io/armmbed/mbed-os-env:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile beats-time app
        run: make
        working-directory: 'apps/beats-time/make'
      - name: Upload UF2
        uses: actions/upload-artifact@v2
        with:
          name: watch.uf2
          path: apps/beats-time/make/build/watch.uf2
