name: Build

on: [pull_request, push]

jobs: 
  build:
    container:
      image: ghcr.io/armmbed/mbed-os-env:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile Starter Project
        run: make
        working-directory: 'apps/beats-time/make'

